### ISSUE TITLE
runEvalAdmix.py error

### ISSUE THREAD

**Issue by evhersh** [stevemussmann/admixturePipeline#10]
Hello. Thanks for the pipeline it has been working really well for me up until this issue! When attempting to run runEvalAdmix.py, I get an error: 

admixuser@6f3a604eb546:/app/data$ runEvalAdmix.py -p filter4.recode -k 1 -K 10 -m popmap_filtered.txt
plink --file filter4.recode --make-bed --out filter4.recode

Traceback (most recent call last):
  File "/app/scripts/python/admixturePipeline/runEvalAdmix.py", line 24, in <module>
    main()
  File "/app/scripts/python/admixturePipeline/runEvalAdmix.py", line 15, in main
    pl.fixFam(input.args.popmap)
  File "/app/scripts/python/admixturePipeline/plink.py", line 41, in fixFam
    (key, val) = line.split()
ValueError: too many values to unpack (expected 2)

Any ideas of what went wrong?

**Comment by stevemussmann** [comment]
Hello, it looks like you may have found a bug. Is there any chance you would be able to send me your input files (.vcf and your population map) as well as the commands you used to run the individual components of the pipeline? I can try to push a fix this weekend.

Thanks,

-Steve

**Comment by evhersh** [comment]
Thanks for the quick response! My vcf is 170 mb, do you have a preferred way for me to send it?

**Comment by stevemussmann** [comment]
Maybe google drive? My email is smussmann at gmail.

**Comment by stevemussmann** [comment]
I don't know if maybe the email is just hung up somewhere, but I haven't seen the files come through yet. Regardless, after looking at the code and error I think I have an idea of what the problem may be, because I parsed the popmap in a slightly different manner in the admixturePipeline.py module vs. the runEvalAdmix.py module. Is there any chance you could just attach your population map file here?

**Comment by evhersh** [comment]
I tried the above command and I'm still getting the same error

**Comment by evhersh** [comment]
Oh, that's embarassing...quite the rookie move on my part to have spaces in the population names! Thanks for your work on this, it is much appreciated.

**Comment by stevemussmann** [comment]
The error I mentioned in my previous post turned out to be somewhat self-inflicted. When I was testing the Docker container on your code, I accidentally ran distructRerun.py outside of the Docker container. That module stores paths to the .q files output from CLUMPAK in a json file so that I avoid parsing the Clumpak output a second time in runEvalAdmix.py. Somehow, when I was averaging the values in the .q files to plot the EvalAdmix output for major/minor clusters, my code was failing to throw an error when it found no files to average. Anyways, I inserted a block of code to test for this error, and report a more informative error message that tells the user what might have happened (i.e., they moved the location of their files after running distructRerun.py, or they somehow managed to run distructRerun.py outside of the Docker container). 

I also updated my code for parsing popmap files so that 1) the code called from admixturePipeline.py and runEvalAdmix.py is now the same, and 2) it now prints a more informative error message when >2 columns are present on any line of the popmap file.

Anyways, I'm doing some last minute tests, then I'm going to push my updated Docker container to Docker Hub. It should be up there later tonight. I also took the opportunity to install the programs wget, less, and vim in the Docker container so that users can view, edit, and pull files from the web more easily from within the container.

**Comment by stevemussmann** [comment]
I'm closing this issue for now. Please feel free to start a new issue or reopen this one if you encounter additional problems.

**Comment by evhersh** [comment]
Thanks Steve! Sorry for getting back to you so late on this, I got sidetracked with another project. I updated to the most recent docker container and everything worked great!
