### ISSUE TITLE
Plotting error

### ISSUE THREAD

**Issue by scintilla9** [stevemussmann/admixturePipeline#6]
Hi, I got the following error messages when plotting corres.png:

" R[write to console]: Error in .External2(C_X11, paste0("png::", filename), g$width, g$height,  : 
  unable to start device PNG

 R[write to console]: In addition: 

R[write to console]: Warning message:

R[write to console]: In (function (filename = "Rplot%03d.png", width = 480, height = 480,  :
R[write to console]: 
 
R[write to console]:  unable to open connection to X11 display ''

Traceback (most recent call last):
  File "/opt/admixturePipeline/runEvalAdmix.py", line 24, in <module>
    main()
  File "/opt/admixturePipeline/runEvalAdmix.py", line 20, in main
    ea.Rcode(input.args.evalAdmixRcode, input.args.minK, input.args.maxK)
  File "/opt/admixturePipeline/evaladmix.py", line 170, in Rcode
    self.grdevices.png(file=output)
  File "/home/cwl/.local/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 199, in __call__
    .__call__(*args, **kwargs))
  File "/home/cwl/.local/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 125, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
  File "/home/cwl/.local/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py", line 45, in _
    cdata = function(*args, **kwargs)
  File "/home/cwl/.local/lib/python3.7/site-packages/rpy2/rinterface.py", line 680, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error in .External2(C_X11, paste0("png::", filename), g$width, g$height,  : 
  unable to start device PNG"

Please kindly provide some suggestion of how to fix this problem. Thanks.

**Comment by stevemussmann** [comment]
Hello, my first guess would be the issue is with your R installation or system configuration, since these are runtime errors from R. My first suggestion would be to determine if R was compiled with cairo enabled - you can test this my running `capabilities()` in R to see if it is true or false. If false, then you need to have the necessary dependencies (cairo libraries) installed on your system, then recompile R.
